settings:
  default_form_open_message: 'Tätä lomaketta ei ole vielä avattu lähetyksille.'
  default_submit_button_label: Lähetä
  default_reset_button_label: Palauta
  default_form_confidential_message: 'Tämä lomake on luottamuksellinen. Sinun täytyy <a href="[site:login-url]/logout?destination=[current-page:url:relative]">kirjautua ulos</a> lähettääksesi se.'
  default_wizard_prev_button_label: '< Edellinen sivu'
  default_wizard_next_button_label: 'Seuraava sivu >'
  default_wizard_start_label: Alkaa
  default_wizard_confirmation_label: Valmis
  default_preview_next_button_label: Esikatselu
  default_preview_label: Esikatselu
  default_draft_button_label: 'Tallenna keskeneräinen'
  default_draft_saved_message: 'Tiedot tallennettu. Voit palata tähän lomakkeeseen myöhemmin ja palauttaa nykyiset tiedot.'
  default_confirmation_message: 'Lisätty uusi lähetys lomakkeelle [webform:title].'
  dialog_options:
    narrow:
      title: Kapea
    normal:
      title: Normaali
    wide:
      title: Leveä
element:
  default_more_title: Lisää
  default_section_title_tag: h2
mail:
  default_body_html: '<p>Lomake on on tallennettu [webform_submission:created]</p> <p>Käyttäjä: [webform_submission:user]</p> <p>Lomakkeen tiedot:</p> [webform_submission:values]'
